name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - release-p2
trigger:
  branches:
    include:
      - release-p2

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: Azure-Static-Web-Apps-polite-forest-00dd33103-variable-group
  steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)/_easiplan/Release/Publish'
      app_location: '/'
      skip_app_build: true
      skip_api_build: true
      is_static_export: true
      verbose: true
      azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_FOREST_00DD33103)'
###### End of Repository/Build Configurations ######

