# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- staging

pool:
  vmImage: 'windows-latest'

variables:
  solutionPath: 'easiplan.app/'
  solution: 'easiplan.app/easiplan.app.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'staging'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solutionPath)\packages.config'
    feedsToUse: 'select'
    vstsFeed: 'f5fe995b-16f5-4546-9628-78f2086cc0c3'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/target:publish /p:ApplicationVersion=${ApplicationVersion} /p:UpdateEnabled=true /p:PublishDir="$(build.ArtifactStagingDirectory)\Publish\\"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
  enabled: false
- task: PublishBuildArtifacts@1
  inputs:
      PathtoPublish: '$(build.ArtifactStagingDirectory)'
      ArtifactName: "Staging"
      publishLocation: Container
